### ISSUE TITLE
Provide the opportunity for stations or deliveries to block the flow of an agent

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/BfROpenLab#106]
A value between 0 and 1 should be definable. 0 means: total block. 1 stands for completely open for flowing. Values in between are probabilities that had to be implemented into the calculation of the score.

**Comment by thoens** [comment]
A solution, that only allows 0/1 (total block/completely open) has been implemented. Needs to be discussed

**Comment by thoens** [comment]
Has been discussed and will stay like it is
