### ISSUE TITLE
Advanced similarity search on strings (e.g. company names, ...)

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#148]
Maybe we can find a library, that does the job.

The algorithm should consider the following things:
- typos at beginning of word are less likely
- "Bäcker Meier" vs "Bäcker Meier GmbH"

**Comment by draaw** [comment]
Dice algorithm implemented doing an even better job

**Comment by thoens** [comment]
- Algorithm does not consider that "typos at beginning of word are less likely"
- levenshtein and jaro-winkler are performing better according this [articale](http://www.stat.cmu.edu/NCRN/PUBLIC/RLClassFiles/Projects/ChenZhao.pdf)

**Comment by thoens** [comment]
Won't be improved
