### ISSUE TITLE
Error during re-execution of SupplyChainReader when DB is older than software

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#150]
Dialog from screenshot is shown and KNIME freezes

![error](https://cloud.githubusercontent.com/assets/6838248/7249662/4006ac86-e81c-11e4-8ce3-a226dea7e437.png)

**Comment by thoens** [comment]
Actually it is not happen during execution, but when closing the config dialog.

1. Open dialog of executed SupplyChainReader
2. Press OK
3. Press OK
4. Error

**Comment by draaw** [comment]
fixed
