### ISSUE TITLE
Missing Data Template Generator: File contains duplicate lots

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#192]
1. Import following xlsx file: [Import File](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/template_generation_duplicates.xlsx)

2. Generate template for Caterer

3. There are multiple entries for lots M01 and M02

![error](https://cloud.githubusercontent.com/assets/6838248/8058546/7263fc3c-0eba-11e5-8d3c-c9172d11800a.png)

**Comment by draaw** [comment]
fixed
