### ISSUE TITLE
Single Template cannot be filled out when lot number for product out is missing

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#193]
Combo box in "Lot Number of Product Out"-column (bottom right on screenshot) only uses lot numbers from the pre-filled template and not manually entered ones

![error](https://cloud.githubusercontent.com/assets/6838248/8062126/7e15a346-0ece-11e5-93e3-5bfe61eeea8b.png)

**Comment by draaw** [comment]
empty lot numbers are now auto-filled, should not occur any longer
