### ISSUE TITLE
Single Template: How to merge two lots?

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#194]
Example:

1. Pre-filled template arrives with two "Pfeffer" lots with different recipients: 700 and 113
2. Supplier notices, that it is actually the same lot.
3. How to merge 700 and 113 in the template?

![question](https://cloud.githubusercontent.com/assets/6838248/8081640/c9d62fb4-0f76-11e5-9598-4bf330428a9c.png)

**Comment by draaw** [comment]
should work now, please check

**Comment by thoens** [comment]
I replaced 113 by 700 in "Products Out" and removed 113 from "Lot Information". When I then import the data, a new delivery occurs, that has not been there before (as you can see in the screenshots).

[Data before](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/before.zip)
[Data after](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/after.zip)

Before:
![before](https://cloud.githubusercontent.com/assets/6838248/8130445/a917f7a6-1112-11e5-9414-a35bdb941411.png)

After:
![after](https://cloud.githubusercontent.com/assets/6838248/8130448/b0edf192-1112-11e5-9f22-c710232fdf98.png)

**Comment by draaw** [comment]
fixed, please check.

**Comment by thoens** [comment]
There is still a new delivery generated (another one than before). That's what I see in the Tracing View:

![error](https://cloud.githubusercontent.com/assets/6838248/8157576/e6a47172-1355-11e5-8c94-7061e644d35b.png)

That's what I would expect as a result:

![expected](https://cloud.githubusercontent.com/assets/6838248/8157588/f6429618-1355-11e5-93fa-78b141703523.png)

**Comment by draaw** [comment]
Yes, I know, at the moment this issue depends on the order of importing the files. If the order is "correct", then you would see the expected result - still open

**Comment by draaw** [comment]
The order of the import is now regulated by the Field "Reporting Date" in the generated template. This field has to be filled, it is mandatory!
