### ISSUE TITLE
Allow to generate pre-filled forward tracing templates

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#195]
Analogous to the generation of pre-filled backward tracing templates

**Comment by draaw** [comment]
please test, but be aware: there might be no auto-generated templates, although you expect some. The reason is that the templates are only generated for deliveries having ZERO successive lots. If there is only one following delivery no template is generated. BTW, the same counts for backward template generation!

**Comment by thoens** [comment]
In "Backtrace_request_2005_Tiefkühlfrucht-Vertrieb.xls" I filled out the "ForwardTracing_Opt" sheet and the resulting deliveries were imported correctly. Then I generated the forward templates for the new stations. The generation worked perfectly and it was easy to fill out the templates.

But the import did not work correctly. The stations I added in the templates did not appear in FoodChain-Lab. Instead duplicate input-deliveries for the forward tracing stations appeared (as you can see in the screenshots).

[Data without Forward Templates](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/before_forward_template.zip)

[Data with Forward Templates](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/after_forward_template.zip)

Before Import:
![before](https://cloud.githubusercontent.com/assets/6838248/8131904/d967c4ee-111d-11e5-972b-cc61e36bf6d4.png)

After Import:
![after](https://cloud.githubusercontent.com/assets/6838248/8131922/feb46694-111d-11e5-8d45-ca323f028b74.png)

**Comment by draaw** [comment]
fixed, please check.

**Comment by thoens** [comment]
Works for me
