### ISSUE TITLE
DB: Skip Import of all files if one file is invalid

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#199]
If the user wants to import multiple files at once and some are invalid, right now all valid files are imported. I think it would be better to import no files at all in this case. Otherwise an incomplete data set is imported, which might be hard to fix.

**Comment by draaw** [comment]
if a user wants to import many files at once, detects an error and the error is resolvable only if all files have to be removed from database, the best way is to refresh the database before importing and import all files then, especially when the user handles the excel file set as complete dataset.
Here, the single template is an independent entity!

**Comment by thoens** [comment]
I do not agree

**Comment by draaw** [comment]
I agree, done, please check

**Comment by thoens** [comment]
Works fine, but the user is not informed, that the valid files are not imported

![image](https://cloud.githubusercontent.com/assets/6838248/10632439/c8438bc0-77e4-11e5-9ffe-d65d82c97a4d.png)

**Comment by draaw** [comment]
fixed, please check
