### ISSUE TITLE
Import Broken: Error Message "Unknown Lot"

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#200]
1. Import following file: [First File](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/import_broken_unknown_lot_1.xlsx)

2. Import following file: [Second File](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/import_broken_unknown_lot_2.xlsx)

3. Following Error Message is shown:

![error](https://cloud.githubusercontent.com/assets/6838248/8126264/3e11b39a-10ed-11e5-8994-ec5ae9806792.png)

**Comment by draaw** [comment]
fixed
