### ISSUE TITLE
How to do Forward Tracing from a Primary Producer?

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#202]
For starting a forward tracing, the "ForwardTracing_Opt" sheet in the Backward-Tracing-Template needs to be filled out. But normally you do not generate Backward-Tracing-Templates for primary producers, since there is no backward tracing to do.

**Comment by draaw** [comment]
You (the manager) normally do not generate these templates, correct, But you can do it for exactly that purpose - and then ask the data gatherer for filling the forward sheet...

**Comment by thoens** [comment]
OK
