### ISSUE TITLE
"ForwardTracing_Opt" deliveries still get simple numbers as DB-ID, should we change this?

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#203]
If you enter information in the "ForwardTracing_Opt" sheet of the Backward-Tracing-Template, the deliveries generated from this get numbers as ID. Other auto generated IDs look like this:

Erdbeeren;107;27;6;2014;27;6;2014;300.0;kg;2005

**Comment by draaw** [comment]
Yes, I think, we should -> done -> please check

**Comment by thoens** [comment]
Works
