### ISSUE TITLE
Allow user to create Forward/Backward Template for specific station

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/BfROpenLab#204]

**Comment by thoens** [comment]
Maybe also for backward template

**Comment by thoens** [comment]
In de.bund.bfr.knime.openkrise.common there are two classes Station and StationDialog, that allow the user to select a specific station. An example on how to use it is in StationDialog.main(String[])

The dialog can be used for backward and forward tracing

**Comment by draaw** [comment]
Please check the solution:
- does it work error free?
- may it stay as it is now?
- please create a new Icon for the ButtonBar

**Comment by thoens** [comment]
I did not get any errors.

Separate buttons for Forward and Backward are still needed

**Comment by draaw** [comment]
Done
