### ISSUE TITLE
Rethink Forward template for case when multiple deliveries go into one lot

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/BfROpenLab#205]

**Comment by thoens** [comment]
If the forward template is generated with multiple ingredients/deliveries and these should go into one lot, the lot information has to be entered multiple time, cause in "Lot Information" one row is generated for each ingredient/delivery

**Comment by draaw** [comment]
we decided that this behaviour is reasonable.
In case of identical lot numbers, the importing routine takes care for all lot information to be identical.
