### ISSUE TITLE
Backward Template: What if one ingredient goes into different lots?

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#206]
I tried it like that, but it did not work:

![image](https://cloud.githubusercontent.com/assets/6838248/8255164/361c684a-169e-11e5-965a-c78d48202180.png)

**Comment by thoens** [comment]
[Data](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/one_ingredient_two_lots.zip)

![test](https://cloud.githubusercontent.com/assets/6838248/8255581/302cb6f8-16a1-11e5-9429-13da0936466a.png)

**Comment by draaw** [comment]
import routine fixed
