### ISSUE TITLE
FoodChain-Lab Installation Tutorial: What to do if KNIME update site missing?

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#211]
If the KNIME update site is not defined in the KNIME settings, FoodChain-Lab cannot be installted.

Cannot complete the install because one or more required items could not be found.
  Software being installed: FoodChain-Lab 1.0.0.201505121032 (de.bund.bfr.knime.openkrise.feature.feature.group 1.0.0.201505121032)
  Missing requirement: FoodChain-Lab 1.0.0.201505121032 (de.bund.bfr.knime.openkrise.feature.feature.group 1.0.0.201505121032) requires 'org.knime.quickform.nodes 0.0.0' but it could not be found

**Comment by draaw** [comment]
reproducible?

**Comment by thoens** [comment]
Cannot reproduce this. Even if I manually delete the KNIME update site from the settings, it's automatically added again when restarting KNIME.
