### ISSUE TITLE
Back/Forward Template: Generate Delivery IDs based on all delivery properties

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#213]
All properties entered by the user should be put in the ID: Name, Lot Number, Date Departure, ...

**Comment by draaw** [comment]
what if two deliveries is indeed identical? Delivered by UPS and the other one by DHL?

**Comment by thoens** [comment]
Currently IDs look like this: Nudeln;111;12;8;2014;13;8;2014;150.0;kg;3001

I think that's already all delivery information, right?
If it is, you can close the ticket

**Comment by draaw** [comment]
All in!
