### ISSUE TITLE
Split Multi-Template into 2 formats: One with lot numbers and one with delivery to delivery relations

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#224]
I think there are 2 scenarios for using the multi template:

1. As a starting point for back tracing: In this case the user must fill out the Stations-tab and the Deliveries-tab with lot numbers (but not the Deliveries2Deliveries-tab). FCL then auto generates back tracing templates for each supplier with all its lots.

2. Everything is imported in one multi template: In this case the user must fill out all tabs (Stations, Deliveries, Deliveries2Deliveries), but should not use lot numbers.

I cannot imagine a case, where it makes sense to fill out both: Deliveries2Deliveries and lot numbers. Using both information is super confusing, since the lot-approach and Deliveries2Deliveries-approach are different ways to do collect the data.

**Comment by draaw** [comment]
Done, both formats are supported now
