### ISSUE TITLE
Template Validator: Error Message when non-existing station ID is used in delivery tab

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#225]
ID "X" does not exist. 

Error Message: null

[XLSX File](https://github.com/SiLeBAT/BfROpenLabResources/raw/master/IssueFiles/Template_Validator_No_Station_With_That_ID.xlsx)

![image](https://cloud.githubusercontent.com/assets/6838248/9994156/390a97b6-607c-11e5-9fa3-e3718acfe8f5.png)

**Comment by draaw** [comment]
fixed, please check

**Comment by thoens** [comment]
I do not get any error message

![image](https://cloud.githubusercontent.com/assets/6838248/10614000/36af743a-7758-11e5-8dd2-d59134a8dfa7.png)

**Comment by draaw** [comment]
jajaja, you are too quick, try again, please
