### ISSUE TITLE
Error/Warning messages after import not reported all at once

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#229]
I tested the attached Excel file WITHOUT Product Out Lot Number with the template validator and was told to state the lot Number of product out. I did not read the full text so I filled in the 'lot number of ingredient'.
-> Feature Request: Change column headlines (Lot Number of Ingredient -> Ingredient Lot Number; Lot Number of "Product Out" -> Product Out Lot Number)
Having added the product out lot number I got ANOTHER error from the validator: "Station 'Abrakadabra' is not correctly defined". This is true and was intended BUT: It would speed up the correction process if all mistakes are shown at once.

[~$Backtrace_request_3001_Caterer 1_ValidationTest LotNoProductOut.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/14839/Backtrace_request_3001_Caterer.1_ValidationTest.LotNoProductOut.xlsx)

Backtrace_request_3001_Caterer.1.xlsx passed the test although not a single ingredient is given. The excel file itself is correct. Would you like to keep it this way or should we give a message like "Test passed. However, the file does not contain information about ingredients."?

[Backtrace_request_3001_Caterer 1.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/14841/Backtrace_request_3001_Caterer.1.xlsx)

The plausibility test concerning ingredient and product out dates works fine.

**Comment by draaw** [comment]
- Column headlines partially changed
- If there are no ongredients a warning is given
- errors "all at once" can still be improved

**Comment by draaw** [comment]
there are new templates in use now not having this issue
