### ISSUE TITLE
Template Validator: Improve error message for duplicate IDs

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#234]
When I use the same ID for two deliveries, I get two different messages for the same error:

1. "Delivery ID '1001' is defined more than once -> Row 32"
2. Delivery defined twice??? -> Row 32; Delivery Id: '1001'

But I do not get the information, in which other row ID '1001' is also used. I would also get rid of the multiple question marks.

[Deliveries from Caterer 01.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/18697/Deliveries.from.Caterer.01.xlsx)

![image](https://cloud.githubusercontent.com/assets/6838248/10672279/417aacac-78ef-11e5-8562-740ae2c4ea5a.png)

**Comment by draaw** [comment]
fixed in GUI importer, online validator will follow in the next deployment circle
please check
