### ISSUE TITLE
Backtrace_request-Template: Sorting of stations

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#239]
When a backtrace request template is exported, the stations are sorted in the order in which they were imported. Because of this, it is hard to find the station needed if you want to fill in the supplier column in the BackTracing sheet.
At the moment the sorting option is activated for the headlines of the stations sheet. However, when trying to find a station in the BackTracing sheet the step to switch to the stations sheet in order to sort all stations is not the first guess.
It would be very helpful if the stations sheet was sorted automatically by 'Name' when the backtrace request template is generated. This sorting could either be performed in the DB before the export or in the excel sheet during the export (before saving to disk).

**Comment by draaw** [comment]
Done.
