### ISSUE TITLE
Backtrace_request-Template: Numbers are saved as text

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#240]
In the exported Backtrace Request Template numbers in the following columns are shown as text:

Stations\Street Number (XLSX exported from DB)
Stations\Postal (XLSX exported from DB)
BackTracing\Ingredient Lot Number (new entry in XLSX after XLSX export from DB)

This is confusing, especially when adding new content in the XLSX template.

**Comment by draaw** [comment]
Street numbers can be text, zip codes and lot numbers as well, therefore the cells are text cells. And Excel then "thinks" that we may have made an error... Thats Excel!
