### ISSUE TITLE
Automatic names of FCL templates: Duplicate station names

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#241]
Until a few weeks ago the usual way to enter stations into the station list of the templates (forward, backward) was to invent a numeric ID and to give a name. Thus, it was useful to have both the ID and the name in the exported template, e.g. 'Backtrace_request_3001_Caterer 1.xlsx'.
Our new naming scheme (ID = Name) makes finding suppliers in the BackTracing sheet much easier. However, now the name of the XLSX file contains duplicate names, e.g. 'Backtrace_request_Caterer 1_Caterer 1.xlsx', leading to file names hard to read and with very long names in case of some stations (e.g. 'Backtrace_request_Dairy Produce Sales and Distribution Ltd._Dairy Produce Sales and Distribution Ltd..xlsx').
To my mind it is sufficient to have the ID in the file name. But, of course, it would be even more user-friendly to have the following options in addition to the ID (AND, OR):
Backtrace_request_[ID]_[Name]_[date of export].xlsx
Especially the date of export is interesting during an outbreak when obtaining new data every day and when several completed templates have already been saved. The date of the last edit (e.g. to be seen in the windows explorer) does not show when the file was exported.

**Comment by draaw** [comment]
Done.
Now, the format is ..._[ID]_[dateofexport].xlsx
