### ISSUE TITLE
Templates: Warning message

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#242]
When copying and pasting into the templates (all 3), a warning message appears which is a lot to read and annoying. I copied stations into the station sheet and got this message for all three templates:

![xlsx warning message](https://cloud.githubusercontent.com/assets/7571357/10884515/af2c753c-8178-11e5-9d72-d5c525665798.png)
What does ToB mean?
It would be more comfortable if the message was suppressed.

**Comment by draaw** [comment]
Indeed, it is annoying.
A tutorial should CLEARLY state that the normal "Paste"-Operation should be AVOIDED.
When pasting elements from Excel->Excel then "text only"-mode should be applied!

**Comment by thoens** [comment]
will be put into tutorial (issue #238)
