### ISSUE TITLE
Import Dialog shows all warnings and not only the ones related to currently imported files

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#243]
First import these two 2 files and you will see warnings:

[BfR_Format_Backtrace_first Caterer 1+2.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/29539/BfR_Format_Backtrace_first.Caterer.1.2.xlsx)
[Backtrace_request_Caterer 1_20151106144503.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/29540/Backtrace_request_Caterer.1_20151106144503.xlsx)

I you now import this file, you will get the same warnings again.

[Backtrace_request_Caterer 2_20151106144459.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/29541/Backtrace_request_Caterer.2_20151106144459.xlsx)

Solution:
Check all warnings before and after each import operation and just show the new warnings to the user

**Comment by draaw** [comment]
Done
