### ISSUE TITLE
DB-Import: No error or warning when file is imported, that references non-existing deliveries

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#245]
E.g. when you import a back- or forward tracing template to an empty DB

**Comment by draaw** [comment]
The question is: is it a bug?
Here, I would say: it is a feature. If, for some reason, the data is provided in that structured template and not in the All-In-One template, there is no reason not to import it. Of course, it needs to be imported including the "non-existing deliveries". And this is what it does.
