### ISSUE TITLE
Forward Template generation not working for some stations

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#246]
First import these files:

[Start_Tracing_Caterers.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/30908/Start_Tracing_Caterers.xlsx)
[Backtrace_request_Caterer 1.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/30909/Backtrace_request_Caterer.1.xlsx)
[Backtrace_request_Caterer 2.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/30910/Backtrace_request_Caterer.2.xlsx)

When I want to generate the forward template for "Frozen Fruit Sales", I just get the following message:

![image](https://cloud.githubusercontent.com/assets/6838248/11065352/19f2943c-87c3-11e5-8473-f45b77a02a93.png)

**Comment by thoens** [comment]
Move it to 1.2, if it's not easy to fix. I do not use the feature in the datacollection tutorial

**Comment by draaw** [comment]
Tracegenerator feedback message updated to "Maybe the selected station '...' has no incoming deliveries"
