### ISSUE TITLE
Highlight Excel cells which require user input

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#247]
Export from DB Excel templates with cells highlighted (e.g. in light blue) which require user input. This would be helpful for cells which need input in EVERY case, meaning that the template would be rejected if this information was omited. Example: Ingredients are given, but not the Product Lot Number or the supplier.
Suggestion for Implementation: Excel cells with conditional formatting ("bedingte Formatierung").

**Comment by draaw** [comment]
Excel sheets need to be as simple as possible, therefore conditional formatting will not be used.
Coloring of cells is not necessary with the new template format
