### ISSUE TITLE
DB: Handling of two Excel templates with partly the same information

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#248]
Situation: Two Excel templates are imported into the FCL DB, which contain information about the same supplier. The information is partly the same (e.g. delivery to three recipients (A, B, C) or two four recipients (A, C, D, E).
-> Inform the user and ask:
"Data in template X is (partly) already saved in the FCL DB.
Overwrite old information or add new data (the latter might lead two duplicates).
Shall identical stations (ID and name are identical) be compared before the import or should they be overwritten?"

**Comment by draaw** [comment]
if the same information is provided then the import routine takes care of not importing duplicates, but automatically detecting that they are the same.
