### ISSUE TITLE
Epidemiology Analytics: Plot cases over time, visualise with deliveries

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#249]
If human cases are imported, create an epidemiological graph with with cases over time (see image). Offer field for incubation period. Display together with deliveries on a time axis => Visualise foods which might be contaminated or which might be of interest during the investigation of foodborne outbreaks.
![foodchain-lab feature](https://cloud.githubusercontent.com/assets/7571357/11243022/ddd35182-8e05-11e5-8166-a35d1b161c96.png)

**Comment by afalenski** [comment]
See also the Outbreaks handbook, page 46

**Comment by thoens** [comment]
This functionality does not fit in the TracingView. A new KNIME node could be created for this. For now, I will just call it "Epidemiology Analytics"

**Comment by thoens** [comment]
Won't be done
