### ISSUE TITLE
Create data exchange interface to food industry

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#251]
During an outbreak authorities and companies work closely together. With an interface between FCL and the companies' delivery software data could be exchanged faster. In addition, this would omit mistakes from manual input or data conversion.

**Comment by afalenski** [comment]
See also the Outbreaks handbook, page 89.

**Comment by draaw** [comment]
this is an always ongoing process - interfaces are always supported as soon as there is a willing company/industry
