### ISSUE TITLE
Template Generation: Wrong error message when non-existing path is used in save dialog

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#260]
Enter a non-existing path in the save dialog as shown in the screenshot (test folder has not been created) and press OK. You will get a message saying: "No new Templates generated. All done?", even when there are templates that should have been created.

![image](https://cloud.githubusercontent.com/assets/6838248/11660654/620282d4-9dce-11e5-8414-c8741627821d.png)

**Comment by draaw** [comment]
done
