### ISSUE TITLE
FoodChain-Lab sometimes freezes on OS X

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#276]

**Comment by thoens** [comment]
@draaw assigned, cause he got a MacBook

the freezing occurred in the TracingView

**Comment by miguelalba** [comment]
i agree

**Comment by draaw** [comment]
Do you have some hints for reproducing the error?

**Comment by thoens** [comment]
It happened in one of the tutorials. That's the only thing I know. I you cannot reproduce it, you can just close the issue

**Comment by draaw** [comment]
not reproducible in the tutorials
