### ISSUE TITLE
NLS Nodes: Compute scaled sensitivity coefficients of parameters before fitting

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#278]

**Comment by thoens** [comment]
http://www.ncbi.nlm.nih.gov/pubmed/23297775
http://ssu.ac.ir/cms/fileadmin/user_upload/Daneshkadaha/dbehdasht/behdasht_imani/art/Parameter-estimation-for.pdf
http://tang.eece.wustl.edu/Kirk/Nonlinear%20Parameter%20Estimation%20Dolan%20lecture.pdf

**Comment by draaw** [comment]
Does not belong to this project
