### ISSUE TITLE
Create SBML/PMF writer and reader

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#288]
@thoens commented on [Thu Feb 05 2015](https://github.com/SiLeBAT/PMM-Lab/issues/36)

---

@thoens commented on [Thu Apr 16 2015](https://github.com/SiLeBAT/PMM-Lab/issues/36#issuecomment-93718977)

handle piecewise function correctly

ASTNode.piecewise(new ASTNode(),
	ASTNode.parseFormula("Y1"), ASTNode.parseFormula("time<lag"),
	ASTNode.parseFormula("Y1+k*(time-lag)"), ASTNode.parseFormula("lag<=time && (time<(lag+(Ymax-Y1)/k))"),
	ASTNode.parseFormula("Ymax"))

**Comment by draaw** [comment]
Does not belong to this project
