### ISSUE TITLE
2017 Backtracing Templates: Show Error message when same lot number is used for different products

### ISSUE THREAD

**Issue by thoens** [SiLeBAT/BfROpenLab#317]
It's unclear to which lot the ingredients should be connected

[StationBacktrace_request_Frozen Fruit Sales_292459172.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/1085701/StationBacktrace_request_Frozen.Fruit.Sales_292459172.xlsx)

**Comment by draaw** [comment]
Done
