### ISSUE TITLE
FCL.Trace View

### ISSUE THREAD

**Issue by OctavioMV** [SiLeBAT/BfROpenLab#319]
If there are many stations and some of them are exactly in the same place and I look for one of them (right button/ select station/) the station selected is marked with blue color but if you want to move it, you click on it and move it but you always move the one which is exactly on the more upper part and not the one selected.

**Comment by OctavioMV** [comment]
[KNIME_FCL.zip](https://github.com/SiLeBAT/BfROpenLab/files/1091375/KNIME_FCL.zip)

**Comment by thoens** [comment]
Fixed! When multiple stations are at the same location and one or more of them are selected, dragging is now applied on the selected stations.
