### ISSUE TITLE
Allow "clear collapsed stations" only for selected stations (tracing view)

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/BfROpenLab#325]
If "clear collapsed stations" is applied, all clusters are cleared. If you just want to clear one cluster, you have to form all other clusters in the tracing view again.

**Comment by draaw** [comment]
There is an option: "Station Selection" -> "Expand from Meta Station". This allows to clear only the selected clusters. Therefore the option "clear collapsed stations" should clear all meta stations - or be removed completely. I would suggest to remove it.

**Comment by ruegenbfr** [comment]
"clear collapsed stations" was removed.
 "Expand from Meta Station" now asks the user whether all meta stations are to be expanded
