### ISSUE TITLE
Tracing View: Rephrase 'Reset observed' warning

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#332]
Workshop participants who pushed the button 'Reset observed' did not dare to klick 'OK' in the warning window stating "This cannot be made undone. Proceed?". This text is perhaps not precise enough so the user thinks of the worst. This text is longer - and hopefully more precise: "The Tracing View will reset its memory on actions that have been done so far so that the undo button will not be able to undo actions up to this point. Proceed?"

**Comment by draaw** [comment]
@afalenski : too long for my taste: what about "Undo/Redo history will be cleared after that action. Proceed?"?

**Comment by afalenski** [comment]
OK.

**Comment by ruegenbfr** [comment]
All reset actions will show this warning now.
