### ISSUE TITLE
Export existing javax annotations

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/BfROpenLab#337]
Please export the package `javax.annotations` in the plugin project `edu.umd.cs.findbugs.annotations`. Some of the annotations from the exported packaged `edu.umd.cs.findbugs.annotations` are deprecated. For example `@NotNull` is replaced by javax `@Nonnull`.

Thanks,
Miguel

**Comment by draaw** [comment]
@miguelalba : I am not sure what you need. Please just do it yourself

**Comment by miguelalba** [comment]
@draaw some javax.annotations are included in that project and back then I wanted to use them. In the end I did not use it in FSK-Lab, so this issue can be closed.
