### ISSUE TITLE
Tracing view: Include warning dialog window unsaved changes

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/BfROpenLab#340]
Changes in the tracing view are not saved if the tracing view is closed or if the "Cancel" button is clicked. There is no warning dialog so far that notifies the user that changes are not saved.

**Comment by draaw** [comment]
@ruegenbfr : please check if possible easily, afraid that not

**Comment by ruegenbfr** [comment]
Unfortunately this behaviour cannot be changed. According to an answer from KNIME (Kilian and others) a ongoing "Cancel" routine can neither be stopped nor can a "Save" programmatically be triggered (within the "Cancel" routine).
