### ISSUE TITLE
Tracing View: Highlight Condition window changes its size and position of scroll bar

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/BfROpenLab#341]
If you have a long list of stations that are highlighted in a certain way and you want to remove one station from the list or add a new station to the list, the size of the Highlight Condition window is increased and the scroll bar jumps to top of the list. Hence, the buttons and fields on the bottom of the list are only available again if the size of the window is reduced, the window is moved upwards and the scroll bar is moved to the bottom of the list. The whole procedure needs to be repeated if you want to add/remove another station.

**Comment by ruegenbfr** [comment]
Issue fixed. Window is not resizing anymore and scrollarea remembers the last position.
