### ISSUE TITLE
Import of All_In_One_Templates ignores Stations

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/BfROpenLab#349]
If an All_In_One_Template is imported without Deliveries but with Stations the Stations are not imported but the message "Import successful!"

**Comment by ruegenbfr** [comment]
Here is an example file:

[All_In_One_Template_with_1_Station_only.xlsx](https://github.com/SiLeBAT/BfROpenLab/files/1449410/All_In_One_Template_with_1_Station_only.xlsx)

**Comment by draaw** [comment]
The message was changed to "Template contains no deliveries"
