### ISSUE TITLE
FCL_DB_Writer shows ArrayIndexOutOfBoundsException on Execute

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/BfROpenLab#353]
I use the SupplyChainReader-Node, a Geocoding-Node and the FCL_DB_Writer. When I try to write back the results from the geocoder the FCL_DB_Writer shows an ArrayIndexOutOfBoundsException on Execute.

Appended files: 
Database for Example: DB_Example.tar.gz
Workflow for Example: Example.zip

[DB_Example.tar.gz](https://github.com/SiLeBAT/BfROpenLab/files/1450185/DB_Example.tar.gz)
[Example.zip](https://github.com/SiLeBAT/BfROpenLab/files/1450190/Example.zip)

**Comment by draaw** [comment]
Done
