### ISSUE TITLE
TracingView: Put Selected Stations as new Column into outport

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/BfROpenLab#369]

**Comment by ruegenbfr** [comment]
The stations table does now contain a column named "Is selected", which indicates whether this station is selected in tracingview. In case the station is member of a meta station, the 'Is selected' value indicates whether the meta station is selected.

**Comment by draaw** [comment]
Selected stations are still not listed in the new column.
It would be great to have the same for deliveries.

**Comment by ruegenbfr** [comment]
The selection status is now correctly set for stations and deliveries.
