### ISSUE TITLE
Enable selection of all stations which received products from a specific station

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#386]
As an outbreak investigator I would like to select all stations which received products from a specific station. Example: A meat processing company sends meat products to 6 wholesale traders and each sends the products to 50 different gastronomy stations (restaurants, hotels, supermarkets). Now I would like to select all gastronomy stations having received products from wholsale trade number 4.

**Comment by draaw** [comment]
Why not make use of the forward trace?

**Comment by ruegenbfr** [comment]
Flexible but perhaps user unfriendly solution:
More complex selections can be performed with knime tools before the TV. The selection can be stored in a new column and can be used in the TracingView.

**Comment by draaw** [comment]
will not be done that way. Is solvable via KNIME and even within the TracingView by making use of the forward trace and further filters
