### ISSUE TITLE
DB merge dialogue: 2 identical lots are shown

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/BfROpenLab#420]
- Import all Starting Templates of the Norovirus scenario plus "StationBacktrace_request_Caterer 1_complete" and "StationBacktrace_request_Caterer 2_complete" from the folder "Backward tracing templates"
- Start DB\Similarity Search\Comparison delivery
Two seemingly identical lots are shown: "C2 Menu 1: [C2M1] ?; ?". The mouseover text shows no differences.
What is the difference between both entries? Do they appear when stations are merged? We either need to display more information (more columns in the similarity search results) or find out whether there truly are two identical lots (could be a search bug or a DB bug).

**Comment by draaw** [comment]
Solved due to changed workflow, i.e. only one entity is choosable at once for similarity search
